### PR TITLE
Quit on ^C

### PR DESCRIPTION
**Pull request by nanaian**

### CODE REVIEW

**Comment by loganmc10** [comment]
Most gui applications dont quit on Ctrl+C

**Comment by nanaian** [comment]
If this doesn't impede normal usage (i.e. from a desktop file), I'd argue its helpful in cases such as during development or when using the CLI; I certainly expected that `m64p --rom path/to/rom` then Ctrl+C would quit, but it just got ignored.

**Comment by loganmc10** [comment]
m64p has a ```--nogui``` option, if launched that way, and providing a ROM, just hitting Esc will close the entire application.

**Comment by ethteck** [comment]
What's the reason to not allow quitting on ctrl+c?

**Comment by loganmc10** [comment]
It's not typical behavior of a GUI based application

**Comment by ethteck** [comment]
Well that's a shame...fork it is, then

**Comment by loganmc10** [comment]
m64p... The Ctrl+C edition. I like it.

**Comment by loganmc10** [comment]
Going to close this, sorry I don't think it's the right fit.

The other problem here is that by default mupen64plus binds Ctrl to "B" and C to "Right Trigger". There is the potential here that someone is going to accidentally close the application while trying to play.

**Comment by nanaian** [comment]
Oh, I see the misunderstanding -- this doesn't work in the GUI! Only in the CLI by sending the SIGINT signal (which is ^C **in the terminal**).

**Pull request closed without merging**
